[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "openpage"
version = "0.1.6"
description = "Python thin wrappers for the openpage Rust browser automation core"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "ip2a", email = "ooooofish@126.com" }
]
dependencies = []
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
packages = ["openpage"]
